# 这些是支持的融资模式平台

github  : # 替换为最多 4 个 GitHub 赞助商启用的用户名，例如 [user1, user2]
patreon   : # 替换为单个 Patreon 用户名
open_collective    : # 替换为单个 Open Collective 用户名
ko_fi     : # 替换为单个 Ko-fi 用户名
tidlift     : # 替换为单个 Tidelift 平台名称/包名称，例如 npm/babel
Community_bridge     : # 名称替换为单个社区桥项目，例如 cloud-foundry
liberapay     : # 替换为单个 Liberapay 用户名
issueshunt     : # 替换为单个 IssueHunt 用户名
lfx_crowdfunding     : # 替换为单个 LFX Crowdfunding 项目名称，例如 cloud-foundry
Polar     : # 替换为单个 Polar 用户名
给我买杯咖啡   : # 替换为单个“买咖啡”用户名
感谢_dev  : # 替换为单个Thanks.dev 用户名
风俗：#替换为最多4个自定义赞助URL，例如[  '链接1'   ,   '链接2' ]
